name: Build Web
# on:
#   push:
#     branches:
#       - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get Dependencies
        id: flutter-get
        run: flutter pub get
      - name: Generate Files
        id: generate-files
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: Build Web
        id: flutter-build-web
        run: flutter build web --release --build-number=$GITHUB_RUN_NUMBER
      - uses: actions/upload-artifact@v3
        with:
          name: Flutter Web Artifacts
          path: ./build/web/
