name: Build Android
# on:
#   push:
#     branches:
#       - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get Dependencies
        id: flutter-get
        run: flutter pub get
      - name: Generate Files
        id: generate-files
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build APK
        id: flutter-build
        run: flutter build apk --release --build-number=$GITHUB_RUN_NUMBER
      - uses: actions/upload-artifact@v3
        with:
          name: Flutter APK binary
          path: ./build/app/outputs/flutter-apk/app-release.apk
